// Generated by scripts/gen-photo-manifest.mjs. Do not edit by hand.
export const photoManifest: Record<string, string> = {
  '5g-home': '/images/5g-home.webp',
  'about-banner': '/images/about-banner.webp',
  'hero-poster': '/images/hero-poster.webp',
  'isat-one': '/images/isat-one.webp',
  'logo-isat': '/images/logo-isat.png',
  'logo-isat-mark': '/images/logo-isat-mark.png',
  'phase-1': '/images/phase-1.webp',
  'phase-2': '/images/phase-2.webp',
  'phase-3': '/images/phase-3.webp',
  'sector-agriculture': '/images/sector-agriculture.webp',
  'sector-education': '/images/sector-education.webp',
  'sector-government': '/images/sector-government.webp',
  'sector-healthcare': '/images/sector-healthcare.webp',
  'sector-manufacturing': '/images/sector-manufacturing.webp',
  'sector-retail': '/images/sector-retail.webp',
};
